# Write your MySQL query statement below
SELECT DEPARTMENT.NAME AS Department, EMPLOYEE.NAME AS Employee,
EMPLOYEE.Salary
FROM DEPARTMENT INNER JOIN EMPLOYEE
ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENTID
WHERE (EMPLOYEE.SALARY, EMPLOYEE.DEPARTMENTID) IN (
    SELECT MAX(SALARY), DEPARTMENTID FROM EMPLOYEE
    GROUP BY DEPARTMENTID
    -- HAVING DEPARTMENTID = DEPARTMENT.ID
)
-- GROUP BY DEPARTMENT;