SELECT DEPARTMENT.NAME AS Department, EMPLOYEE.NAME AS Employee, EMPLOYEE.Salary
FROM DEPARTMENT INNER JOIN EMPLOYEE
ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENTID
WHERE 3 > (
    SELECT COUNT(DISTINCT SALARY) FROM EMPLOYEE E
    WHERE E.SALARY > EMPLOYEE.SALARY
    AND E.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
);